[
    {
        "id": 239721705,
        "name": "CVE-2018-1335-Python3",
        "full_name": "N0b1e6\/CVE-2018-1335-Python3",
        "owner": {
            "login": "N0b1e6",
            "id": 46476997,
            "avatar_url": "https:\/\/avatars3.githubusercontent.com\/u\/46476997?v=4",
            "html_url": "https:\/\/github.com\/N0b1e6"
        },
        "html_url": "https:\/\/github.com\/N0b1e6\/CVE-2018-1335-Python3",
        "description": null,
        "fork": false,
        "created_at": "2020-02-11T09:19:57Z",
        "updated_at": "2020-02-11T09:21:58Z",
        "pushed_at": "2020-02-11T09:20:33Z",
        "stargazers_count": 0,
        "watchers_count": 0,
        "forks_count": 0,
        "forks": 0,
        "watchers": 0,
        "score": 0
    }
]