[
    {
        "id": 179225702,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNzkyMjU3MDI=",
        "name": "CVE-2019-6690",
        "full_name": "brianwrf\/CVE-2019-6690",
        "private": false,
        "owner": {
            "login": "brianwrf",
            "id": 8141813,
            "node_id": "MDQ6VXNlcjgxNDE4MTM=",
            "avatar_url": "https:\/\/avatars0.githubusercontent.com\/u\/8141813?v=4",
            "gravatar_id": "",
            "url": "https:\/\/api.github.com\/users\/brianwrf",
            "html_url": "https:\/\/github.com\/brianwrf",
            "followers_url": "https:\/\/api.github.com\/users\/brianwrf\/followers",
            "following_url": "https:\/\/api.github.com\/users\/brianwrf\/following{\/other_user}",
            "gists_url": "https:\/\/api.github.com\/users\/brianwrf\/gists{\/gist_id}",
            "starred_url": "https:\/\/api.github.com\/users\/brianwrf\/starred{\/owner}{\/repo}",
            "subscriptions_url": "https:\/\/api.github.com\/users\/brianwrf\/subscriptions",
            "organizations_url": "https:\/\/api.github.com\/users\/brianwrf\/orgs",
            "repos_url": "https:\/\/api.github.com\/users\/brianwrf\/repos",
            "events_url": "https:\/\/api.github.com\/users\/brianwrf\/events{\/privacy}",
            "received_events_url": "https:\/\/api.github.com\/users\/brianwrf\/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https:\/\/github.com\/brianwrf\/CVE-2019-6690",
        "description": "It is a simple PoC of Improper Input Validation in python-gnupg 0.4.3 (CVE-2019-6690).",
        "fork": false,
        "url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690",
        "forks_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/forks",
        "keys_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/keys{\/key_id}",
        "collaborators_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/collaborators{\/collaborator}",
        "teams_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/teams",
        "hooks_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/hooks",
        "issue_events_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/issues\/events{\/number}",
        "events_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/events",
        "assignees_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/assignees{\/user}",
        "branches_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/branches{\/branch}",
        "tags_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/tags",
        "blobs_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/git\/blobs{\/sha}",
        "git_tags_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/git\/tags{\/sha}",
        "git_refs_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/git\/refs{\/sha}",
        "trees_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/git\/trees{\/sha}",
        "statuses_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/statuses\/{sha}",
        "languages_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/languages",
        "stargazers_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/stargazers",
        "contributors_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/contributors",
        "subscribers_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/subscribers",
        "subscription_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/subscription",
        "commits_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/commits{\/sha}",
        "git_commits_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/git\/commits{\/sha}",
        "comments_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/comments{\/number}",
        "issue_comment_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/issues\/comments{\/number}",
        "contents_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/contents\/{+path}",
        "compare_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/compare\/{base}...{head}",
        "merges_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/merges",
        "archive_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/{archive_format}{\/ref}",
        "downloads_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/downloads",
        "issues_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/issues{\/number}",
        "pulls_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/pulls{\/number}",
        "milestones_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/milestones{\/number}",
        "notifications_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/notifications{?since,all,participating}",
        "labels_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/labels{\/name}",
        "releases_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/releases{\/id}",
        "deployments_url": "https:\/\/api.github.com\/repos\/brianwrf\/CVE-2019-6690\/deployments",
        "created_at": "2019-04-03T06:34:48Z",
        "updated_at": "2019-04-08T14:49:17Z",
        "pushed_at": "2019-04-03T07:57:14Z",
        "git_url": "git:\/\/github.com\/brianwrf\/CVE-2019-6690.git",
        "ssh_url": "git@github.com:brianwrf\/CVE-2019-6690.git",
        "clone_url": "https:\/\/github.com\/brianwrf\/CVE-2019-6690.git",
        "svn_url": "https:\/\/github.com\/brianwrf\/CVE-2019-6690",
        "homepage": null,
        "size": 3,
        "stargazers_count": 6,
        "watchers_count": 6,
        "language": "Perl",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 6,
        "default_branch": "master",
        "score": 28.895666
    },
    {
        "id": 166676940,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNjY2NzY5NDA=",
        "name": "CVE-2019-6690-python-gnupg-vulnerability",
        "full_name": "stigtsp\/CVE-2019-6690-python-gnupg-vulnerability",
        "private": false,
        "owner": {
            "login": "stigtsp",
            "id": 75371,
            "node_id": "MDQ6VXNlcjc1Mzcx",
            "avatar_url": "https:\/\/avatars2.githubusercontent.com\/u\/75371?v=4",
            "gravatar_id": "",
            "url": "https:\/\/api.github.com\/users\/stigtsp",
            "html_url": "https:\/\/github.com\/stigtsp",
            "followers_url": "https:\/\/api.github.com\/users\/stigtsp\/followers",
            "following_url": "https:\/\/api.github.com\/users\/stigtsp\/following{\/other_user}",
            "gists_url": "https:\/\/api.github.com\/users\/stigtsp\/gists{\/gist_id}",
            "starred_url": "https:\/\/api.github.com\/users\/stigtsp\/starred{\/owner}{\/repo}",
            "subscriptions_url": "https:\/\/api.github.com\/users\/stigtsp\/subscriptions",
            "organizations_url": "https:\/\/api.github.com\/users\/stigtsp\/orgs",
            "repos_url": "https:\/\/api.github.com\/users\/stigtsp\/repos",
            "events_url": "https:\/\/api.github.com\/users\/stigtsp\/events{\/privacy}",
            "received_events_url": "https:\/\/api.github.com\/users\/stigtsp\/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https:\/\/github.com\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability",
        "description": null,
        "fork": false,
        "url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability",
        "forks_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/forks",
        "keys_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/keys{\/key_id}",
        "collaborators_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/collaborators{\/collaborator}",
        "teams_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/teams",
        "hooks_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/hooks",
        "issue_events_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/issues\/events{\/number}",
        "events_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/events",
        "assignees_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/assignees{\/user}",
        "branches_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/branches{\/branch}",
        "tags_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/tags",
        "blobs_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/git\/blobs{\/sha}",
        "git_tags_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/git\/tags{\/sha}",
        "git_refs_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/git\/refs{\/sha}",
        "trees_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/git\/trees{\/sha}",
        "statuses_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/statuses\/{sha}",
        "languages_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/languages",
        "stargazers_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/stargazers",
        "contributors_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/contributors",
        "subscribers_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/subscribers",
        "subscription_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/subscription",
        "commits_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/commits{\/sha}",
        "git_commits_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/git\/commits{\/sha}",
        "comments_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/comments{\/number}",
        "issue_comment_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/issues\/comments{\/number}",
        "contents_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/contents\/{+path}",
        "compare_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/compare\/{base}...{head}",
        "merges_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/merges",
        "archive_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/{archive_format}{\/ref}",
        "downloads_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/downloads",
        "issues_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/issues{\/number}",
        "pulls_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/pulls{\/number}",
        "milestones_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/milestones{\/number}",
        "notifications_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/notifications{?since,all,participating}",
        "labels_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/labels{\/name}",
        "releases_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/releases{\/id}",
        "deployments_url": "https:\/\/api.github.com\/repos\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability\/deployments",
        "created_at": "2019-01-20T15:29:46Z",
        "updated_at": "2019-09-22T10:45:25Z",
        "pushed_at": "2019-09-21T17:35:44Z",
        "git_url": "git:\/\/github.com\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability.git",
        "ssh_url": "git@github.com:stigtsp\/CVE-2019-6690-python-gnupg-vulnerability.git",
        "clone_url": "https:\/\/github.com\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability.git",
        "svn_url": "https:\/\/github.com\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability",
        "homepage": null,
        "size": 35,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "Python",
        "has_issues": false,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "forks_count": 1,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 1,
        "open_issues": 0,
        "watchers": 1,
        "default_branch": "master",
        "score": 14.508592
    }
]