[
    {
        "id": 230083007,
        "name": "django_cve201919844",
        "full_name": "andripwn\/django_cve201919844",
        "owner": {
            "login": "andripwn",
            "id": 52893492,
            "avatar_url": "https:\/\/avatars2.githubusercontent.com\/u\/52893492?v=4",
            "html_url": "https:\/\/github.com\/andripwn"
        },
        "html_url": "https:\/\/github.com\/andripwn\/django_cve201919844",
        "description": "PoC for CVE-2019-19844 ( https:\/\/www.djangoproject.com\/weblog\/2019\/dec\/18\/security-releases\/ )",
        "fork": false,
        "created_at": "2019-12-25T10:05:48Z",
        "updated_at": "2020-06-13T18:57:32Z",
        "pushed_at": "2020-06-13T18:57:41Z",
        "stargazers_count": 6,
        "watchers_count": 6,
        "forks_count": 0,
        "forks": 0,
        "watchers": 6,
        "score": 0
    }
]